before_install: 
  - "eval \"${MATRIX_EVAL}\""
language: cpp
matrix: 
  include: 
    - 
      env: 
        - "MATRIX_EVAL=\"TESTENV=build && CC=gcc && CXX=g++\""
      os: linux
      script: 
        - make
    - 
      env: 
        - "MATRIX_EVAL=\"TESTENV=build && CC=gcc && CXX=g++\""
      os: osx
      script: 
        - make